routes/web.php
<?php

use App\Http\Controllers\Auth\WelcomeController;
use App\Http\Controllers\BenefitController;
use App\Http\Controllers\BenefitCorrectionController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\DiagnosticTestController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\DoseController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\InsuranceCarrierController;
use App\Http\Controllers\LaboratoryController;
use App\Http\Controllers\ManagementDiagnosticTestController;
use App\Http\Controllers\MedicineController;
use App\Http\Controllers\PathologyController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PatientEnrollController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PharmacyChainController;
use App\Http\Controllers\PharmacyController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SpecialtyController;
use App\Http\Controllers\TrackingController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Spatie\WelcomeNotification\WelcomesNewUsers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'landing');

Route::view('/refund/list_pharmacy', 'refund.list_pharmacy');
Route::view('/refund/list_pharmacy/details', 'refund.details_refund');

// RUTAS NUEVAS PARA EL FLUJO DE FARMACIA
//benefit
Route::controller(BenefitController::class)->middleware('auth')->prefix('benefits')->as('benefits.')->group(function () {
    Route::get('/invoice', 'index_invoice')->name('invoice');
    Route::get('{benefit}/letter-authorization', 'showAuthorizationLetterStatus')->name('letter_authorization.show');
    Route::post('{benefit}/letter-authorization', 'updateAuthorizationLetterStatus')->name('letter_authorization.update');
    Route::get('/upload_invoice/{benefit}', 'upload_invoice')->name('upload_invoice');
    Route::get('/authorization', 'index_authorization')->name('authorization');
    Route::patch('/patient/{benefit}', 'load_invoice')->name('patient.update');

    Route::get('benefits/{benefit}/management', 'benefit_management')->name('benefits.management');
    Route::patch('benefits/{benefit}/management', 'status_update')->name('status.benefits.management');
    Route::post('benefits-new', 'newBenefitStore')->name('new.benefits');
    Route::apiResource('benefits', BenefitController::class);
});

Route::group(['middleware' => ['web', WelcomesNewUsers::class]], function () {
    Route::get('welcome/{user}', [WelcomeController::class, 'showWelcomeForm'])->name('welcome');
    Route::post('welcome/{user}', [WelcomeController::class, 'savePassword']);
});

Route::controller(PatientController::class)->middleware('auth')->prefix('patients')->as('patients.')->group(function () {
    Route::get('/', 'list_patients')->name('list_patients');
    Route::get('/diagnostic-test', 'patient_diagnostic')->name('diagnostic_test');
    Route::get('import/template', 'downloadImportTemplate')->name('download_import_template');
    Route::post('import', 'import')->name('import');
    Route::get('/patient/{patient}/personal_information', 'personal_information')->name('personal_information');
    Route::patch('patient/{patient}/update', 'update_patient')->name('update_patient');
    Route::get('patient/{patient}/treatment', 'treatment')->name('treatment');
    Route::patch('patient/{patient}/treatment', 'update_treatment');
    Route::delete('{patient}', 'destroy')->name('delete');
    Route::patch('{patient}/restore', 'restore')->name('restore')->withTrashed();
});

//Pruebas diagnosticas gestión
Route::controller(ManagementDiagnosticTestController::class)->middleware('auth')->group(function () {
    Route::get('management-diagnostic-tests/{management_diagnostic_test}/management', 'management_diagnostic_test')->name('management-diagnostic-test');
    Route::patch('management-diagnostic-tests/{management_diagnostic_test}/management', 'updateManagement')->name('management.update');
    Route::patch('management-diagnostic-tests/{management_diagnostic_test}/test', 'updateTest')->name('test.update');
    Route::post('management-diagnostic-tests-new', 'newManagementDiagnosticTestStore')->name('new.management-diagnostic-test');
    Route::apiResource('management-diagnostic-tests', ManagementDiagnosticTestController::class);
});

// Segumiento
Route::controller(TrackingController::class)->middleware('auth')->group(function () {
    Route::get('trackings', 'show')->name('tracking.management_show');
    Route::get('trackings/edit/{tracking}', 'edit')->name('tracking.management_edit');
    Route::get('trackings/update/{tracking}', 'update')->name('tracking.management_update');
    Route::get('trackings/patients', 'patients')->name('tracking.patients');
    Route::get('trackings/patient/{patient}', 'store')->name('trackings.store');
    Route::get('trackings/{tracking}', 'managementTracking')->name('tracking.management');
});

Route::middleware('auth')->prefix('corrections')->name('corrections.')->group(function () {
    Route::controller(BenefitCorrectionController::class)->prefix('benefits')->name('benefits.')->group(function () {
        Route::get('', 'index')->name('index');
        Route::get('{benefit}', 'edit')->name('edit');
        Route::post('{benefit}', 'update')->name('update');
        Route::delete('{benefit}', 'destroy')->name('delete');
        Route::patch('{benefit}/restore', 'restore')->name('restore')->withTrashed();
    });
});

//Reports
Route::view('reports/', 'report_list.index')->name('reports.index')->middleware('auth');

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    //Management
    Route::view('management/', 'management.index')->name('management.index')->middleware('auth');

    //Roles
    Route::controller(RoleController::class)->group(function () {
        Route::get('management/roles/all', 'getRoles')->name('roles_all');
        Route::post('management/roles/{role}/assign-permission', 'syncPermissions');
        Route::apiResource('management/roles', RoleController::class);
        Route::delete('management/roles/{role}/force-delete', 'forceDelete')->name('roles.force_delete')->withTrashed();
        Route::patch('management/roles/{role}/restore', 'restore')->name('roles.restore')->withTrashed();

        //Users
        Route::get('management/users/{user}/assign-rol', 'allRoles')->name('management.assignrol');
    });

    //Permisos
    // Route::get('management/permissions/all', [PermissionController::class, 'getPermissions'])->name('permissions_all');
    Route::controller(PermissionController::class)->group(function () {
        Route::get('management/roles/{role}/assign-permission', 'allPermissions')->name('management.assignpermission');
        Route::apiResource('management/permissions', PermissionController::class);
        Route::delete('management/permissions/{permission}/force-delete', 'forceDelete')->name('permissions.force_delete')->withTrashed();
        Route::patch('management/permissions/{permission}/restore', 'restore')->name('permissions.restore')->withTrashed();
    });

    Route::controller(UserController::class)->group(function () {
        //Users
        Route::post('management/users/{user}/assign-rol', 'syncRoles');
        Route::apiResource('management/users', UserController::class);
    });

    Route::resources([
        //Farmacias
        'management/pharmacies' => PharmacyController::class,

        //Cadenas
        'management/pharmacy-chains' => PharmacyChainController::class,

        //Especialidades
        'management/specialties' => SpecialtyController::class,

        //Doctores
        'management/doctors' => DoctorController::class,

        //Países
        'management/countries' => CountryController::class,

        //Ciudades
        'management/cities' => CityController::class,

        //Aseguradoras
        'management/insurance-carriers' => InsuranceCarrierController::class,

        //Hospitales
        'management/hospitals' => HospitalController::class,

        //Patologías
        'management/pathologies' => PathologyController::class,

        //Medicinas
        'management/medicines' => MedicineController::class,

        //Dosis
        'management/doses' => DoseController::class,

        //Laboratorios
        'management/laboratories' => LaboratoryController::class,

        //Pruebas Diagnosticas
        'management/diagnostic-tests' => DiagnosticTestController::class,
    ]);
});

Route::controller(PatientEnrollController::class)->prefix('landing')->name('landing.')->group(function () {
    Route::get('', 'index')->name('index');
    Route::get('select-country', 'showSelectCountryView')->name('show_select_country_view');

    Route::prefix('{country}')->group(function () {
        Route::get('consent', 'showConsentView')->name('show_consent_view');
        Route::get('register', 'showRegistrationForm')->name('show_registration_form');
        Route::POST('register', 'store')->name('store');
        Route::get('end', 'end_landing')->name('end');
    });
});

Route::view('/portal', 'portal.index')->middleware('auth');

// RUTAS SUPERVISOR/SUPERADMIN
Route::view('/supervisor/user/create', 'supervisor.user.create');
Route::view('/supervisor/user/list', 'supervisor.user.list');

Route::post('upload_doctors', [DoctorController::class, 'ImportDoctors'])->name('ImportDoctors');
Route::post('upload_hospitals', [HospitalController::class, 'ImportHospital'])->name('ImportHospital');

resources/views/landing/consents/base.blade.php
@extends('layouts.landing.app')
@section('content')
    <div class="row pt-5">
        <div class="col">
            <div class="card card-body ">

                <div class="row-reverse">
                    <div class="col d-flex justify-content-center my-5">
                        <img src="{{ url('img/logo_novartis.png') }}" alt="" class="w-25">
                    </div>
                    <div class="col d-flex justify-content-center pt-4">
                        <label for="" class="lead font-weight-bold text-dark">CONSENTIMIENTO INFORMADO</label>
                    </div>
                    <div class="row mx-auto">
                        @yield('consent')
                    </div>
                    <div class="col d-flex justify-content-center">
                        <a href="javascript:;" data-toggle="modal" data-target="#exampleModalCenter1" class="btn btn-lg" style="background-color: #221F1F">ACEPTAR Y CONTINUAR</a>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="modal fade" id="exampleModalCenter1" ata-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true" aria-labelledby=" exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg " role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row-reverse p-3">
                        <div class="col d-flex justify-content-center align-items-center mb-3">
                            <img src="{{ url('svg/11.svg') }}" alt="">
                        </div>
                        <div class="col d-flex justify-content-center ">
                            <label for="" class="h3 text-center text-dark" style="font-weight: bold">Confirma que ha <br>
                                leído y aceptado el consentimiento informado</label>
                        </div>
                        <div class="col my-4">
                            <p class="h5 text-center">A continuación complete el formulario de <br>
                                su inscripción al plan de beneficios de Novartis.</p>
                        </div>
                        <div class="col d-flex justify-content-center">
                            <a href="{{ route('landing.show_registration_form',request()->route()->parameters()) }}" class="btn text-white w-25" style="background: #221F1F">ACEPTO</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/landing/consents/ecuador.blade.php
@extends('landing.consents.base')
@section('consent')
    <div class="col-11 mx-auto d-flex justify-content-center p-4 my-5" style="border: solid 1px black; ">
        <div class=" perfect-scrollbar-on " style="min-height: 40vh; max-height: 40vh; overflow: auto; ">
            <div class="row-reverse">
                <div class="col">
                    <label for="" class="h4 font-weight-bold">Aviso de privacidad para
                        pacientes</label>
                </div>
                <div class="col">
                    <p class="h5">
                        Novartis Ecuador S.A., con domicilio en Av. Amazonas N37-29, Quito, Ecuador, correo electrónico
                        datospersonales.ecuador@novartis.com y teléfono 0223990100 (en adelante “Novartis”) ha generado un
                        programa de apoyo que otorga los siguientes beneficios a los pacientes que hayan sido prescritos por
                        su médico tratante con los medicamentos Cosentyx® o Xolair®.
                    </p>
                </div>
                <div class="col">
                    <p class="h5">A través de este programa, el paciente podrá recibir los siguientes beneficios:
                    </p>
                </div>
                <div class="col ">
                    <ul>
                        <li style="list-style: none"><i class="h5">1. Descuento para pacientes que realicen la
                                compra del tratamiento a través de puntos de venta autorizados y no cuenten con seguro
                                privado</i></li><br>
                        <li style="list-style: none"><i class="h5">2. Cobertura del co-pago del tratamiento
                                según póliza de aseguradora</i></li><br>
                        </li><br>
                    </ul>
                </div>
                <div class="col">
                    <p class="h5">Para lo anterior, si usted continúa con su registro en esta página,
                        entenderemos que otorga su consentimiento para el tratamiento de datos personales registrados con
                        base en el Aviso de Privacidad; así como la aceptación de términos y condiciones del
                        programa<br><br>
                    </p>
                </div>
                <div class="col">

                    <ul>
                        <li style="list-style: none"><i class="h5">1. Nombre
                                completo del
                                paciente</i></li><br>
                        <li style="list-style: none"><i class="h5">2. Fecha de
                                nacimiento</i>
                        </li><br>
                        <li style="list-style: none"><i class="h5">3. Correo
                                electrónico</i>
                        </li><br>
                        <li style="list-style: none"><i class="h5">4. Teléfono</i>
                        </li><br>
                        <li style="list-style: none"><i class="h5">5. Producto
                                prescrito</i>
                        </li><br>
                        <li style="list-style: none"><i class="h5">6. Seleccione
                                patología y
                                dosis</i></li><br>
                    </ul>

                </div>

                <div class="col">
                    <p class="h5">Con base en lo anterior, los datos personales que Novartis recabe podrán ser
                        tratados únicamente para las siguientes finalidades:
                    </p>
                </div>

                <div class="col">
                    <p class="h5">Finalidades primarias, estas son aquellas necesarias para poder concretar la
                        relación con usted y que cumplen el objetivo principal de la recolección, en caso de no estar de
                        acuerdo con estas no podrán realizarse las acciones descritas: (i) Para que usted pueda participar
                        en programas de pacientes y/o de investigación clínica; (ii) Para que usted pueda participar y/o
                        colaborar en diversos eventos o foros relacionados con la salud, ya sea presenciales o digitales
                        (remotos); (iii) Para integrar bases de datos acorde con las otras finalidades aquí descritas; (iv)
                        Para cumplir la legislación aplicable; (v) Para mantener la relación jurídica que pueda generarse;
                        (vi) En algunos casos, Novartis podrán realizar las acciones que considere necesarias, a efecto de
                        comprobar, directamente o a través de terceros, la veracidad de los datos proporcionados y; (vii)
                        Permitirle el acceso a cualquiera de nuestras instalaciones.</p>
                </div>
                <div class="col">
                    <p class="h5">
                        Finalidades secundarias o complementarias, no necesarias para cumplir con el objetivo principal de
                        la recolección: adicionalmente, se podrán utilizar sus datos personales: (i) Para invitarlo a
                        participar en diferentes programas, eventos, foros y conferencias relacionados con la salud ya sea
                        en forma presencial o remota; (ii) Para ofrecerle y/o enviarle información relacionada con la salud
                        y, en algunos casos, muestras médicas; (iii) Para, previa codificación y/o anonimización de los
                        datos, agregarlos a otros y realizar análisis estadísticos, de generación de modelos de información
                        y/o perfiles de comportamiento actual y predictivo y/o investigaciones clínicas o científicas; (iv)
                        Participar en encuestas; (v) Para cumplir con nuestros procesos internos y; (vi) Para dar
                        seguimiento a los eventos adversos que hayan tenido que ser reportados conforme a la legislación
                        aplicable. Adicionalmente, y únicamente para las finalidades descritas más arriba, Novartis podrá
                        compartir sus datos con otras filiales de Novartis o su tercero designado.
                    </p>
                </div>
                <div class="col">
                    <p class="h5">
                        Los datos personales se almacenarán en un banco de datos personales titularidad de Novartis o su
                        tercero designado<br><br>

                        Se deja constancia de que la entrega de los datos personales es facultativa. [Sin embargo, en caso
                        de que el paciente no desee brindar sus datos, no será posible brindarle los beneficios del
                        Programa].<br><br>

                        Asimismo, se le informa que los datos personales que se recabarán podrían ser remitidos por Novartis
                        a servidores, filiales y/o proveedores que se encuentren fuera de Ecuador, pero siempre con el único
                        propósito de cumplir con las finalidades descritas más arriba y respetando en todo momento la
                        seguridad y confidencialidad de los datos.<br><br>

                        Con base en lo anterior, Novartis da a conocer a usted el uso de la información para el tratamiento
                        de sus datos personales y personales sensibles con base en las finalidades aquí descritas y cumple
                        con la legislación aplicable sobre datos personales y personales sensibles.<br><br>

                        Al dar click en el botón “Aceptar y continuar”, yo (nombre y apellido) otorgo mi consentimiento y
                        autorizo a Novartis para el procesamiento, dentro y/o fuera del país, de mis datos personales y
                        personales sensibles que recabe con base el presente documento.<br><br>

                        Manifiesto que mi consentimiento es voluntario y que no es requerimiento para poder adquirir mi
                        medicamento.<br><br>

                        Finalmente reconozco que: (i) El presente consentimiento tendrá la misma vigencia que el Programa o
                        la de mi participación en este, (ii) Tengo el derecho de solicitar acceso, la corrección, o incluso,
                        revocar mi consentimiento en cualquier momento respecto a mis datos personales y (iii) Cualquier
                        solicitud respecto a mi información personal, debe realizarse a través del siguiente correo:
                        datospersonales.ecuador@novartis.com.<br><br>

                        Novartis garantiza que la información personal estará debidamente protegida a través de la
                        implementación de medidas administrativas, técnicas y físicas tendientes a prevenir la pérdida, el
                        uso indebido, el acceso no autorizado, la divulgación o la alteración de sus datos personales. La
                        información podrá ser bloqueada y almacenada por un plazo de 10 años, contados a partir del
                        cumplimiento del objetivo para el que se recabó la misma.<br><br>

                        Para más información sobre nuestro aviso de privacidad puede ingresar al siguiente enlace Política
                        de privacidad | CANDEAN.Novartis.com<br><br>


                    </p>
                </div>

                {{-- <div class="col">
                <p class="h5"><span class="font-weight-bold">*NOTA: </span>Si quien firma no es directamente el paciente y es un cuidador, familiar o representante legal por favor completar la información relacionada al cuidador y colocar sus datos:</p>
            </div> --}}
                <div class="col my-5">
                    <div class="row mb-3">
                        <div class="col">
                            <p class="h5">Nombre y apellido del cuidador, familiar o represente legal (si aplica):</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col d-flex justify-content-center">
                            <p class="h5">Firma: ______________________________ </p>
                        </div>
                        <div class="col d-flex justify-content-center">
                            <p class="h5">Fecha: ______________________________ </p>
                        </div>
                    </div>
                </div>
                <div class="col my-5 d-flex justify-content-center">
                    <img src="{{ url('img/logo_novartis.png') }}" alt="" class="w-25">
                </div>
            </div>

        </div>
    </div>
@endsection